<!DOCTYPE html>
<html>
<head>
    <title>Inbizsys - Supplier Report</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        @media print {
            @page { size: A4; margin: 1cm; }
            footer { position: fixed; bottom: 0; width: 100%; border-top: 1px solid #ccc; font-size: 10px; padding-top: 5px; }
            .no-print { display: none; }
            .page-number:after { content: "Page " counter(page); }
        }
    </style>
</head>
<body class="p-8" onload="window.print()">
    <header class="mb-8 border-b-2 border-indigo-600 pb-4">
        <h1 class="text-3xl font-bold uppercase">Inbizsys</h1>
        <p class="text-slate-500">Empowering Industrial Excellence</p>
    </header>

    <table class="w-full text-sm border">
        <thead>
            <tr class="bg-slate-100 border-b">
                <th class="p-2 text-left">Supplier Name</th>
                <th class="p-2 text-left">Email</th>
                <th class="p-2 text-left">Phone</th>
                <th class="p-2 text-left">Address</th>
            </tr>
        </thead>
        <tbody>
            @foreach($suppliers as $supplier)
            <tr class="border-b">
                <td class="p-2">{{ $supplier->name }}</td>
                <td class="p-2">{{ $supplier->email }}</td>
                <td class="p-2">{{ $supplier->phone }}</td>
                <td class="p-2">{{ $supplier->address }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <footer>
        <div class="flex justify-between">
            <span class="page-number"></span>
            <span>Report Generated By: {{ auth()->user()->name ?? 'System Admin' }}</span>
        </div>
        <div class="text-center mt-1 italic text-slate-400">Inbizsys - Empowering Industrial Excellence</div>
    </footer>
</body>
</html>